const SearchActionTypes = {
  FETCH_SEARCH_RESULTS_START: 'FETCH_SEARCH_RESULTS_START',
  FETCH_SEARCH_RESULTS_SUCCESS: 'FETCH_SEARCH_RESULTS_SUCCESS',
  FETCH_SEARCH_RESULTS_FAILURE: 'FETCH_SEARCH_RESULTS_FAILURE',
  FETCH_SEARCH_RESULTS_FINISHED: 'FETCH_SEARCH_RESULTS_FINISHED',
};

export default SearchActionTypes;
