const UpDownActionsTypes = {
  UP_START: 'UP_START',
  UP_SUCCESS: 'UP_SUCCESS',
  UP_FAILURE: 'UP_FAILURE',
  UP_FINISHED: 'UP_FINISHED',
  DOWN_START: 'DOWN_START',
  DOWN_SUCCESS: 'DOWN_SUCCESS',
  DOWN_FAILURE: 'DOWN_FAILURE',
  DOWN_FINISHED: 'DOWN_FINISHED',
};

export default UpDownActionsTypes;
