const SubeBajaActionsTypes = {
  SUBE_START: 'SUBE_START',
  SUBE_SUCCESS: 'SUBE_SUCCESS',
  SUBE_FAILURE: 'SUBE_FAILURE',
  SUBE_FINISHED: 'SUBE_FINISHED',
  BAJA_START: 'BAJA_START',
  BAJA_SUCCESS: 'BAJA_SUCCESS',
  BAJA_FAILURE: 'BAJA_FAILURE',
  BAJA_FINISHED: 'BAJA_FINISHED',
};

export default SubeBajaActionsTypes;
